apiVersion: v1
kind: Service
metadata:
  name: autodeploy60
  namespace: namespace-workflow-1717140690595
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: autodeploy60
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000